spring:
  datasource:
    from:
      jdbc-url: jdbc:mysql://192.168.222.128:3306/master?characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
    to:
      jdbc-url: jdbc:mysql://192.168.222.128:3306/slave1?characterEncoding=utf8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456